version: 2.1
workflows:
  build-deploy:
    jobs:
      - build

jobs:
  build:
    machine: true
    resource_class: large
    steps:
      - run: docker context create multiarch_builder
      - run: docker buildx create multiarch_builder
      - run: docker context use multiarch_builder
      - run: docker buildx use multiarch_builder
      - run: docker buildx inspect --bootstrap
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run: docker build --push --platform linux/amd64,linux/arm/v7,linux/arm64 --tag iamrony777/alpine-pandas:latest .