version: 2.1
workflows:
  build-deploy:
    jobs:
      - build

jobs:
  build:
    docker: 
      - image: jdrouet/docker-with-buildx:stable
    resource_class: large
    steps:

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run: |-
          docker context create multiarch_builder
          docker buildx create multiarch_builder
          docker buildx use multiarch_builder
          docker buildx inspect --bootstrap
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker build --push --platform linux/amd64,linux/arm/v7,linux/arm64 --tag iamrony777/alpine-pandas:latest .