version: 2.1
workflows:
  build-deploy:
    jobs:
      - build

jobs:
  build:
    machine: true
    resource_class: large

    steps:
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run: docker context create multiarch_builder
      - run: docker context use multiarch_builder
      - run: docker buildx create --use multiarch_builder
      - run: docker buildx inspect --bootstrap
      - run: ls ..
      - run: ls ../project
      - run: ls .
      # - run: git clone https://github.com/iamrony777/alpine-pandas.git
      # - run: cd alpine-pandas
      # - run: git checkout circleci-project-setup
      # - run: docker buildx build --push --platform linux/amd64,linux/arm/v7,linux/arm64 --tag iamrony777/alpine-pandas:latest ~/project/Dockerfile