version: 2.1
workflows:
  build-deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: large

    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run: docker run --privileged --rm tonistiigi/binfmt --install all
      - run: docker context create multiarch_builder
      - run: docker context use multiarch_builder
      - run: docker buildx create --use multiarch_builder
      - run: docker buildx inspect --bootstrap
      - run: docker buildx build --push --platform linux/amd64,linux/arm/v7,linux/arm64 --tag iamrony777/alpine-pandas:latest https://github.com/iamrony777/alpine-pandas.git#"$CIRCLE_BRANCH"